--
-- bearbeitet von: Anna-Lisa Merkel
--

-- MySQL Script generated by MySQL Workbench
-- Sun Jan 10 22:09:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FruitsForFriends
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FruitsForFriends
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FruitsForFriends` DEFAULT CHARACTER SET utf8 ;
USE `FruitsForFriends` ;

-- -----------------------------------------------------
-- Table `FruitsForFriends`.`ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FruitsForFriends`.`ingredients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `description` VARCHAR(50) NOT NULL,
  `category` VARCHAR(100) NOT NULL,
  `origin` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `description_UNIQUE` (`description` ASC));


-- -----------------------------------------------------
-- Table `FruitsForFriends`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FruitsForFriends`.`addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `street` VARCHAR(100) NOT NULL,
  `number` VARCHAR(5) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `zipCode` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `FruitsForFriends`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FruitsForFriends`.`accounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `username` VARCHAR(30) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `firstname` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(50) NOT NULL,
  `gender` ENUM('u', 'm', 'f') NOT NULL,
  `birthdate` DATE NOT NULL,
  `addresses_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  INDEX `fk_accounts_addresses_idx` (`addresses_id` ASC),
  CONSTRAINT `fk_accounts_addresses`
    FOREIGN KEY (`addresses_id`)
    REFERENCES `FruitsForFriends`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `FruitsForFriends`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FruitsForFriends`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `orderdate` DATE NOT NULL,
  `totalPrice` DECIMAL(5,2) NOT NULL,
  `accounts_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_accounts1_idx` (`accounts_id` ASC),
  CONSTRAINT `fk_orders_accounts1`
    FOREIGN KEY (`accounts_id`)
    REFERENCES `FruitsForFriends`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `FruitsForFriends`.`mixed_smoothies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FruitsForFriends`.`mixed_smoothies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `accounts_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mixed_smoothies_accounts1_idx` (`accounts_id` ASC),
  CONSTRAINT `fk_mixed_smoothies_accounts1`
    FOREIGN KEY (`accounts_id`)
    REFERENCES `FruitsForFriends`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `FruitsForFriends`.`drinks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FruitsForFriends`.`drinks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `name` VARCHAR(50) NOT NULL,
  `typeOfDrink` ENUM('j', 's') NOT NULL,
  `taste` VARCHAR(20) NOT NULL,
  `price` DECIMAL(4,2) NOT NULL,
  `mixed_smoothies_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_drinks_mixed_smoothies1_idx` (`mixed_smoothies_id` ASC),
  CONSTRAINT `fk_drinks_mixed_smoothies1`
    FOREIGN KEY (`mixed_smoothies_id`)
    REFERENCES `FruitsForFriends`.`mixed_smoothies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `FruitsForFriends`.`orderitems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FruitsForFriends`.`orderitems` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `quantity` INT NOT NULL,
  `orders_id` INT NOT NULL,
  `drinks_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orderitems_orders1_idx` (`orders_id` ASC),
  INDEX `fk_orderitems_drinks1_idx` (`drinks_id` ASC),
  CONSTRAINT `fk_orderitems_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `FruitsForFriends`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orderitems_drinks1`
    FOREIGN KEY (`drinks_id`)
    REFERENCES `FruitsForFriends`.`drinks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `FruitsForFriends`.`composition_of_drinks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FruitsForFriends`.`composition_of_drinks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `amountInPercent` INT NOT NULL,
  `drinks_id` INT NOT NULL,
  `ingredients_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_composition_of_drinks_drinks1_idx` (`drinks_id` ASC),
  INDEX `fk_composition_of_drinks_ingredients1_idx` (`ingredients_id` ASC),
  CONSTRAINT `fk_composition_of_drinks_drinks1`
    FOREIGN KEY (`drinks_id`)
    REFERENCES `FruitsForFriends`.`drinks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_composition_of_drinks_ingredients1`
    FOREIGN KEY (`ingredients_id`)
    REFERENCES `FruitsForFriends`.`ingredients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
